name: Post-Push Automation

on:
  # Trigger the workflow on push to main branch
  push:
    branches: ["main"]

  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build LOVE package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: ./libs ./main.lua 
          package-path: ./dist/game.love

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: game-LOVE
          path: ./dist/game.love